### ISSUE TITLE
npm install giving lot of errors

### ISSUE THREAD

**Issue by jessicastorm1986** [sjmelia/electron-boilerplate-sqlite#13]
it throws so many errors, please try and let me know if it works at your end, in my side it says node-gyp errors, unable to download and what not.

I have tried with alternate internet connection, but problem is same.

**Comment by sjmelia** [comment]
Errors with `node-gyp` are usually going to be platform specific, because it's building the particular combination of electron & sqlite for your platform. Supporting `node-gyp` is a bit outside the scope of my project, but if you paste in the particular errors you're seeing i'll have a quick look.

**Comment by asadadams** [comment]
Encountered the error below , can you help out

`Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> sqlite3@3.1.13 install f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\build\deps\action_before_build.vcxproj]
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)

Error output:
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=f:\\Ongoing\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=f:\\Ongoing\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64"
gyp ERR! cwd f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "f:\\Ongoing\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd f:\Ongoing\electron-boilerplate-sqlite\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Use\AppData\Roaming\npm-cache\_logs\2019-03-01T18_00_41_890Z-debug.log

    at ChildProcess.childProcess.once.code (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\src\util\util.ts:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\src\util\util.ts:99:3)
    at f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\src\yarn.ts:146:11
From previous event:
    at rebuild (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\out\yarn.js:81:22)
    at f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\src\yarn.ts:15:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at installOrRebuild (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\out\yarn.js:33:21)
    at f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\src\cli\install-app-deps.ts:34:2
    at Generator.next (<anonymous>)
From previous event:
    at main (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\out\cli\install-app-deps.js:36:21)
    at Object.<anonymous> (f:\Ongoing\electron-boilerplate-sqlite\node_modules\electron-builder\out\cli\install-app-deps.js:76:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! electron-boilerplate-sqlite@1.0.0 postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-boilerplate-sqlite@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Use\AppData\Roaming\npm-cache\_logs\2019-03-01T18_00_42_022Z-debug.log`

**Comment by sjmelia** [comment]
Did you try reading the error message? It says “The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.“ - have you tried this?

**Comment by asadadams** [comment]
Tried reinstalling the windows-build-tools and now get the error below

`Rebuilding native production dependencies for win32:x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> sqlite3@3.1.13 install c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\build\deps\action_before_build.vcxproj(20,3): error MSB4019: The imported project "c:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)

Error output:
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\Users\\Use\\Desktop\\electron-boilerplate-sqlite-master\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=c:\\Users\\Use\\Desktop\\electron-boilerplate-sqlite-master\\node_modules\\sqlite3\\lib\\binding\\electron-v1.8-win32-x64"
gyp ERR! cwd c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Use\\Desktop\\electron-boilerplate-sqlite-master\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Use\AppData\Roaming\npm-cache\_logs\2019-03-02T08_04_12_930Z-debug.log

    at ChildProcess.childProcess.once.code (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\src\util\util.ts:136:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\src\util\util.ts:99:3)
    at c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\src\yarn.ts:146:11
From previous event:
    at rebuild (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\out\yarn.js:81:22)
    at c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\src\yarn.ts:15:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at installOrRebuild (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\out\yarn.js:33:21)
    at c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\src\cli\install-app-deps.ts:34:2
    at Generator.next (<anonymous>)
From previous event:
    at main (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\out\cli\install-app-deps.js:36:21)
    at Object.<anonymous> (c:\Users\Use\Desktop\electron-boilerplate-sqlite-master\node_modules\electron-builder\out\cli\install-app-deps.js:76:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! electron-boilerplate-sqlite@1.0.0 postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-boilerplate-sqlite@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Use\AppData\Roaming\npm-cache\_logs\2019-03-02T08_04_13_102Z-debug.log`

**Comment by sjmelia** [comment]
This error message says “The imported project "c:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk”

I googled that. This is the first result.

https://stackoverflow.com/questions/41695251/c-microsoft-cpp-default-props-was-not-found

Have you tried any of these suggestions?

**Comment by asadadams** [comment]
Just tried some of the solutions and still didn't work . One of the solutions is to install visual studio 2015. Don't have one at the moment so will try that one and see if I will still have those errors . And thanks 😊

**Comment by sjmelia** [comment]
Any joy? Hope you managed to get it working!
