### ISSUE TITLE
sqlite3 fails with file

### ISSUE THREAD

**Issue by eljeffeg** [sjmelia/electron-boilerplate-sqlite#19]
I've updated this boilerplate to use the latest, but I'm having an issue where upon release creation, the mac app crashes if a file is used instead of memory.  The file gets created, but the app just crashes.  `:memory:` works fine.  I expect this is an issue with node-sqlite3 and not this boilerplate, but hope to get a good example of a working implementation for my electron app.  The app itself works fine if I do npm start and even works on the mac app if run in a debugger `lldb`, but for some reason, fails when run normally.  I noticed that node-sqlite3 does have a [5.0.1  release](https://github.com/mapbox/node-sqlite3/commit/833f5cc1332b9213a17873f42a3d3a18dca5afc1), but it hasn't been published to npm and I can't get it to build from source.  Tested on both Electron 9 & 10.  In any case, I'm struggling with it, so I figured I'd pass the info to bigger brains than I.

### This works fine.
`var db = new sqlite3.Database(':memory:');`
### This fails with the release.
`var db = new sqlite3.Database('test.db');`
### Here is the updated package.json.
```
{
  "name": "electron-boilerplate-sqlite",
  "productName": "Electron boilerplate with sqlite",
  "description": "Starter for your electron + sqlite application",
  "version": "1.0.0",
  "author": "Kolley Kibber <kolley.kibber@example.com>",
  "copyright": "© 2016, Kibber Ltd.",
  "homepage": "http://example.com",
  "license": "MIT",
  "main": "app/app.js",
  "build": {
    "appId": "com.example.electron-boilerplate-sqlite",
    "files": [
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ]
  },
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "release": "electron-builder"
  },
  "dependencies": {
    "sqlite3": "^5.0.0"
  },
  "devDependencies": {
    "electron": "^10.1.5",
    "electron-builder": "^22.9.1"
  }
}
```

**Comment by eljeffeg** [comment]
I figured out the issue.  In Windows, doing `var db = new sqlite3.Database('test.db');` simply writes a file to the application directory.  On Mac, it's not structured like that and you just don't have permission to write into the App's container.  You have to place the file into the userData directory or some other writable location and not `__dirname`.  Feel free to use this updated package.json.

**Comment by sjmelia** [comment]
Hi jeffg2k, sounds great! Have you got a PR in mind? I can't see the updated package.json
