### ISSUE TITLE
Fails using webpack

### ISSUE THREAD

**Issue by pamtbaau** [sjmelia/electron-boilerplate-sqlite#4]
The template works fine when installed as described. However, when adding webpack to the mix, it fails with all sorts of errors.

Any suggestions on how to use this boilerplate in combination with webpack?

**Comment by sjmelia** [comment]
Hi there sorry for the long absence.

Having googled around I think you already managed to solve this :) The problem boils down to WebPack being unable to bundle a native library (sqlite) so you need to exclude it from the bundling as you describe in your comment [here](https://github.com/mapbox/node-sqlite3/issues/698#issuecomment-318857027).

I'm going to close the case thanks.

**Comment by pamtbaau** [comment]
Yes, I found a solution and didn't think of closing this question. My bad. Hope it didn't take too much of your time...
