### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by silentpride** [sjmelia/electron-boilerplate-sqlite#5]
Hi!
I run "npm install" and just failed.
here is the log:

Error output:
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1020:11)
gyp ERR! stack     at TLSWrap.onread (net.js:568:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\js\\node\\node.exe" "E:\\js\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\js\\project\\sqlite\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\lib\\binding\\electron-v1.7-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\\js\\project\\sqlite\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\lib\\binding\\electron-v1.7-win32-x64"
gyp ERR! cwd E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\sqlite3
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.7-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\sqlite3\lib\binding\electron-v1.7-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "E:\\js\\node\\node.exe" "E:\\js\\project\\sqlite\\electron-boilerplate-sqlite\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\sqlite3
node-pre-gyp ERR! node -v v6.11.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\js\\node\\node.exe" "E:\\js\\node\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "sqlite3"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\js\project\sqlite\electron-boilerplate-sqlite\npm-debug.log

    at ChildProcess.childProcess.once.code (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\src\util\util.ts:136:14)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
From previous event:
    at spawn (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\src\util\util.ts:99:3)
    at E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\src\yarn.ts:146:11
From previous event:
    at rebuild (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\out\yarn.js:81:22)
    at E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\src\yarn.ts:15:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\out\yarn.js:33:21)
    at E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\src\cli\install-app-deps.ts:34:2
    at next (native)
From previous event:
    at main (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\out\cli\install-app-deps.js:36:21)
    at Object.<anonymous> (E:\js\project\sqlite\electron-boilerplate-sqlite\node_modules\electron-builder\out\cli\install-app-deps.js:76:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "E:\\js\\node\\node.exe" "E:\\js\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-boilerplate-sqlite@1.0.0 postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-boilerplate-sqlite@1.0.0 postinstall script 'install-app-deps'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-boilerplate-sqlite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-boilerplate-sqlite
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-boilerplate-sqlite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\js\project\sqlite\electron-boilerplate-sqlite\npm-debug.log

I have Visual Studio 2013, Python 2.7.11, Vue.js 2.5.9, Node 7.9.0, Windows 7, win64.
I don't why it doesn't work.

**Comment by sjmelia** [comment]
Hi there!

`ECONNRESET` suggests a network connectivity error and the `TLSWrap` part suggests that this could be specifically a problem with HTTPS. This can be caused by proxy, firewall or other network problems - have a look at this case which might help: https://github.com/nodejs/node-gyp/issues/645

Thanks!

**Comment by silentpride** [comment]
THX, I will try
