### ISSUE TITLE
Documentation would be good

### ISSUE THREAD

**Issue by lucasgonze** [sjmelia/electron-boilerplate-sqlite#7]
Howdy, 

This a great resource for a baseline electron+sqlite build that I can use to reality check problems with sqlite in my main electron app. But I'm not quite sure what you did here, so I'm not sure how to apply this information to other projects.

I see the example JS calling on sqlite3 in index.html. And I can see these parts of package.json:

<pre>`
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "release": "build"
  },
  "dependencies": {
    "sqlite3": "^3.1.8"
  },
  "devDependencies": {
    "electron": "^1.4.10",
    "electron-builder": "^10.8.1"
  }
`</pre>

Also, you had a note about needing to run-script the postinstall step. Got it.

But aside from that, I'm wondering what the exact differences there were between your code and the starting point, so that I can do approximately the same things in my own app. A git diff would be ideal. 

Just an idea.

**Comment by sjmelia** [comment]
Hey! Thanks for your kind words & sorry for my delay in replying.

It's a truly minimal project - you could try diffing a brand new project from `npm init` to see the changes? I take on board what you're saying for future boilerplate - if i'd committed after the `npm init` and you could see the changes through it would definitely make it a better structured example. I'll bear that in mind in future.

I think you've really hit the nail on your head with your examples though - I don't think there is much more to it than that; primarily thanks to `electron-builder`.
