### ISSUE TITLE
After build not load the template

### ISSUE THREAD

**Issue by jempis** [sjmelia/electron-boilerplate-sqlite#8]
Hi, [sorry for my english]
i have a project started by this(electron-boiler-sqlite).
this project is composed:
 - Angularjs
 - bootstrap (with template [gentelella](https://github.com/marcinn/genitalia))
 - express
 - sqlite

When i run: npm run start ("electron ."), it's all ok 
this the result
![run_start](https://user-images.githubusercontent.com/16114820/35343843-e911d424-012b-11e8-945b-4e8756e42c70.png)

Contrariwise when i run : npm run release, i have any problem.
The build ends successfully, but when open the project the result is this:

![run_release](https://user-images.githubusercontent.com/16114820/35344078-82f03d1a-012c-11e8-9895-0801142dca00.png)

Have you any idea for resolve this problem?

Thank
Jempis

**Comment by sjmelia** [comment]
Hi Jempis!

Your English is great.

I suspect it's going to be a problem with your imagery and CSS resources not being included in the build. This could be a number of issues e.g. if you're using webpack it could be a problem there. Unfortunately, it's difficult to tell without seeing more of your project.

Thanks,

**Comment by jempis** [comment]
Hi sjmelia,
thank you for response.

Then this is my package.json

`{
  "name": "AllogiatiManager",
  "version": "0.1.0",
  "description": "AllogiatiManager",
  "main": "main.js",
  "author": "Jempis",
  "build": {
    "appId": "com.overapp.allogiatimanager",
    "files": [
      "./**/*",
      "node_modules/**/*",
      "package.json",
      "main.js"
    ]
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron .",
    "release": "build",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "dependencies": {
    "body-parser": "^1.18.2",
    "express": "^4.10.8",
    "method-override": "^2.3.10",
    "morgan": "^1.9.0",
    "sequelize": "^4.28.5",
    "sqlite3": "^3.1.8"
  },
  "devDependencies": {
    "electron": "^1.4.10",
    "electron-builder": "^19.55.2"
  }
}`

and then this my structure project:
![structure_project](https://user-images.githubusercontent.com/16114820/35614208-93d0e746-066e-11e8-8a24-c124e16768f2.png)

where
 - 'app' folder contains the NodeJS "BackEnd"
 - 'public' folder is the AngulaJS "FrontEnd"
 - server.js file is the express nodejs server
 - main.js is the electron file

 If you want other information i can attach the whole project.

thanks,
Jempis

**Comment by jempis** [comment]
I'm a stupid!
I have a github repository for this project, you can show directly:
[https://github.com/jempis/AladorHousedsManager](https://github.com/jempis/AladorHousedsManager)

**Comment by sjmelia** [comment]
Hi Jempis - sorry for not replying in so long.

I hope you managed to fix this problem - unfortunately debugging issues with packaging styles/images is outside the scope of this project, sorry! I can only refer you to the documentation for `electron-builder`. Thanks.
